#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/make/make-4.3.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip m4 perl" 

export ZOPEN_GIT_URL="https://git.savannah.gnu.org/git/make.git"
export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz"

export ZOPEN_EXTRA_CFLAGS="-D_LARGE_TIME_API -D_OPEN_MSGQ_EXT -D_OPEN_SYS_FILE_EXT=1 -D_OPEN_SYS_SOCK_IPV6 -DPATH_MAX=1024 -D_UNIX03_SOURCE -D_UNIX03_THREADS -D_UNIX03_WITHDRAWN"
export ZOPEN_EXTRA_LDFLAGS=""

if [ "${ZOPEN_TYPE}x" = "TARBALLx" ]; then
	export ZOPEN_BOOTSTRAP=skip
	export ZOPEN_CHECK="${PWD}/make-4.3/make"
fi

export ZOPEN_MAKE="./build.sh"
export ZOPEN_CHECK="${ZOPEN_ROOT}/makecheck.sh"

zopen_check_results()
{
#!/bin/sh
# make should have 10 failures or less
#
chk="$2_check.log"

set -x
failures=$(grep ".* Tests in .* Categories Failed" ${chk} | cut -f1 -d' ')
if [ ${failures} -gt 10 ]; then
  exit 2
else
  exit 1
fi
}

